name: Sync to Hugging Face Space
on:
  push:
    branches: [main] # Or 'master', depending on your default branch
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to Hugging Face
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: git push https://harmanbajwa:$HF_TOKEN@huggingface.co/spaces/harmanbajwa/RoadSense_AI main --force
